### ISSUE TITLE
Per World Configuration Not Saving

### ISSUE THREAD

**Issue by justinforlenza** [thibaulthenry/cosmos#3]
I am trying to enable per-world features in the cosmos.conf, however, every time I restart the server, these config changes get overridden, to be the default.

**Comment by thibaulthenry** [comment]
Hey,

The only reason this might happen is that you are editing the configuration file while the server is running.

Because when your server is started the configuration is loaded in memory and when server stops this configuration in memory is saved to the file, overridding the modification you may have done manually.

Make sure to stop your server before editing the configuration file manually.


Otherwise there is an ingame command that can save the configuration while the server is running, for example with inventories :

`cm perworld inventories true --save-config`

**Comment by justinforlenza** [comment]
Okay thank you, that solved the issue
